### ISSUE TITLE
Lua memory.writebyte() partially broken for SXROM variant of MMC1

### ISSUE THREAD

**Issue by Andypro1** [TASVideos/fceux#64] opened 2019-06-25 23:52 UTC
**What does work:**
  Calling `memory.writebyte(0x6878, 0xff);` works just fine in an MMC1 title like vanilla Metroid.

**What does not work:**
  Calling `memory.writebyte(0x6878, 0xff);` does not work in an SXROM-based variant of the game, the Zelda 1 / Metroid 1 Crossover Randomizer.  The write (and others in the same range) simply fail silently.

It's possible the way the PRG-RAM banks are loaded/swapped somehow affect FCEUX's cheat engine.

I guessed at a fix which did work, but I am hesitant to create a pull request as I have no idea if my solution would have unintended side effects as I am unfamiliar with the codebase.

**Where:**
  Function `void FCEU_CheatSetByte(uint32 A, uint8 V)` in `src/cheat.cpp`

**Working change:**

The check for the address `A` being in the CPU address space was copied to the top of the method to run first.

```
void FCEU_CheatSetByte(uint32 A, uint8 V) {
	if(A < 0x10000) {
		BWrite[A](A, V);
		return;
	}

   if(CheatRPtrs[A>>10])
    CheatRPtrs[A>>10][A]=V;
   else if(A < 0x10000)
    BWrite[A](A, V);
}
```

**Comment by zeromus** [comment] 2019-07-17 21:23
lua's memory_writebyte should not work through the cheat API. That's stupid. I don't even want to trace through all that crap. It should go straight to the <0x10000 check and BWrite.
It seems all our packed-in scripts use it for accessing memory only so they wouldn't even notice we made the change.
@vadosnaprimer can you confirm you agree that this logic in fceux predates any sense of best practices and needs to be revised to work as memorydomain systembus would rather than this weird broken mess? 
We would need to update the docs too

**Comment by vadosnaprimer** [comment] 2019-07-17 21:30
I don't remember anything about memory writing other than it's implemented in a super complicated manner. I can't have an opinion without diving into it again, for which I just don't have time right now :(

**Comment by zeromus** [comment] 2019-07-17 21:33
Mainly I meant, if it works any way other than as systembus, do you think it's a good idea to change it or are you willing to say "meh, whatever it did before, who cares.. it should work like systembus"

**Comment by vadosnaprimer** [comment] 2019-07-17 21:50
The problem is I haven't seriously used either approach so in addition to no opinion I also have no experience here. Having an option would be the best but we don't include memory domain as an argument to lua mem access IIRC.

**Comment by zeromus** [comment] 2019-07-17 21:52
OK, let's change the `memory` functions to work like systembus (that is go through BWrite and ARead directly) and then add `legacymemory` functions which work the same as the current `memory` functions; and update the docs. @Andrypro1 if you can do that, then I'll work with you on merging it.

**Comment by Andypro1** [comment] 2019-07-17 23:53
Sure.  Does this look like it will work?

ffcc6c080fbb035331373fb648c92140561749cb

The memory read functions did not use the cheat engine, so only the write function needed a legacy implementation.

I have tested memory_writebyte() and memory.legacywritebyte() in the lua console and they both seem to behave as expected.

If this looks okay to you, I can submit it as a pull request.

**Comment by zeromus** [comment] 2019-07-18 14:57
looks okay to me

**Comment by Andypro1** [comment] 2019-07-18 15:12
Pull request #67 sent.

**Comment by bbbradsmith** [comment] 2019-11-23 04:30
Pull request merged.

**Closed by bbbradsmith** 2019-11-23 04:30 UTC
