### ISSUE TITLE
City Connection (mapper 87) has glitched graphics if savestates have been used

### ISSUE THREAD

**Issue by Dwedit** [TASVideos/fceux#46] opened 2019-04-05 01:00 UTC
NES Mapper 087 (found in datalatch.cpp) has no bus conflicts.  However, after loading state, the `bus_conflict` variable suddenly is 1 instead of 0, breaking the mapper.

Edit:

Seems to happen only if:
* You played the US version of City Connection previously (CNROM Mapper with Bus Conflicts), and saved state, saving a 'BUSC' value of 1 into the savestate 
* You loaded *that state* while playing the Japanese version of City Connection (overwriting the mapper's `bus_conflict` variable to the savestate's value of 1)
* You see the game crash, reset the game, play the game, and make savestates.

Came up with a workaround:

In file datalatch.cpp:
```
static void StateRestore(int version) {
	if (WSync != CNROMSync)
	{
		bus_conflict = 0;
	}
	WSync();
}
```
This forces `bus_conflict` to be correct and to disregard whatever value it read from the savestate.

edit again: Should the "Bus Conflict" flag even be in the savestate in the first place?

**Comment by g0me3** [comment] 2019-04-05 08:42
lol usually loading a save state from a different ROM cause game crash in most cases, you very lucky that city connection suffer only from mapper unintended behaviour. can't see the reason to fix something that shouldn't usually happen (you specifically must disable savestate names with sha1 of saved rom then also...

**Comment by g0me3** [comment] 2019-04-05 08:43
also there may be other mappers with mus conflict stored or not, so this fix is not a correct solution for this i think

**Comment by bbbradsmith** [comment] 2019-04-05 20:08
I don't think you should fix it with that StateRestore change. If anything, you should fix it by deleting the line that adds 'BUSC' to the save state map in the first place. I'd wonder if this has any unintended consequences, but with a quick examination of the code it seems like it would be fine.

Unfortunately datalatch.cpp is shared with a ton of mappers and systemically affects a lot of games, so for that reason I'd be scared to make a change like this.

As for other mappers which may store bus conflict (a search for BUSC turned up 3), they can be addressed separately or not at all, since the meaning of of it is mapper defined anyway.

**Comment by g0me3** [comment] 2019-04-12 21:00
souds reasonably, merged, now i think its fixed

**Closed by g0me3** 2019-04-12 21:00 UTC
