### ISSUE TITLE
Mapper 035 not working correctly (nesdev wiki says its a duplicate of mapper 209, but its missing specific registers)

### ISSUE THREAD

**Issue by therealinfidelity** [TASVideos/fceux#37] opened 2019-02-17 14:20 UTC
I'm having an issue with mapper 035, the nesdev wiki says it is a duplicate of mapper 209, but its not letting me use certain registers.

1: unable to set PRG-ROM bank type with register $D000, it's always set to 8kb chunks even if I set $D000 to either 8kb/16kb/32kb, it's always 8kb.
2: unable to swap out hard wired bank using register $8003.
3: unable to use register $D003 to access1 additional 512k PRG-ROM. It looks like because of the PRG-ROM only using 8kb chunks, it's unavailable?

I havent even begun to mess with the CHR, because I want to make sure everything else is working properly as i advance in learning the mapper usage. But if the nesdev wiki says 35 is a duplicate of 209, then i feel the FCEUX build i have (2.2.3) has mapper 35 functioning incorrectly.

-infidelity
NES rom hacker

**Comment by g0me3** [comment] 2019-02-17 14:41
and again as I said on sourceforge lol
mapper 35 is not a duplicate of 209, this mapper I assigned for one particular dump here http://cah4e3.shedevr.org.ru/dumping_2009.php#070309 and i don't know why nesdev wiki claimed it should be 209, it's not, not try to get it to function the same. it is a mmc3 pirate hacked clone.

**Closed by g0me3** 2019-02-17 14:41 UTC
