### ISSUE TITLE
"Real" Zapper controller support

### ISSUE THREAD

**Issue by JasonWThompson** [TASVideos/fceux#130] opened 2020-07-16 21:04 UTC
Currently if an input is set to Zapper, the emulator will use the mouse to emulate the Zapper. This makes playing with a real zapper difficult or impossible. I'm aware of the other challenges such as timing, CRT sensing, etc..., but those can be worked around.

I propose to allow the zapper to be able to be represented by two button states. One button will represent whether the trigger is being pushed and the other can represent whether the sensor is seeing light. This would determine what is read at $4017 (or $4016 if the zapper is plugged into port1).

**Comment by bbbradsmith** [comment] 2020-07-16 22:10
What does it mean to play FCEUX with a real zapper?

As for controlling the light sensor with a separate button, I'm not sure what you would do with that? Actual games that use the zapper require the light sensor to be on and off with sub-frame timing. The zapper itself filters out light that does not turn on and off at high frequencies, it's basically a "scanline" sensor. The actual window of time where $4017 starts registering the light is a fairly narrow portion of the frame...

FCEUX's zapper implementation is a little bit annoying because it does not update the light sensor position except when you click the button. That's the main problem, IMO. You can't do anything that involves aiming without pulling the trigger. As far as I know this only matters for a small handful of homebrew games (e.g. "ZapPing" from [Action 53](https://wiki.nesdev.com/w/index.php/Action_53)) or test ROMs ([zapper tests](http://forums.nesdev.com/viewtopic.php?f=9&t=13021), [Zap Ruder](https://github.com/pinobatch/zap-ruder/releases/))... I haven't yet run across any older games where it mattered where the zapper was pointed when not pulling the trigger.

So... if anything I would just suggest having the sensor position update always and not only when the trigger is pulled, rather than trying to assign it to a button? I'm curious what you mean about playing with a real zapper though. How does that work?

**Comment by JasonWThompson** [comment] 2020-07-17 02:13
Thanks for the question, @bbbradsmith . To clarify, I mean I'm literally working on a real NES Zapper to USB adapter that will show up as a simple two button HID game pad. One of the buttons will be "pressed" when the zapper's trigger is pressed and the other button will be "pressed" when the zapper sees light.

As for the hardware challenges, I'm aware of them. Based on my research, there are some myths around the Zapper. It has already been [demonstrated that the Zapper can work on an LCD screen](http://neslcdmod.com/).  The two hardware issues being the screen delay and the light sensor. If it is merely a case of seeing the right thing at the right frame, then a two button controller should be enough to represent the states of the zapper.

**Comment by bbbradsmith** [comment] 2020-07-17 02:47
The NES zapper _can't_ work on most LCD screens, though I do think some models with a CF backlight flicker at a high enough frequency to get through its filter. There are several clone zappers without such a strong filter. The NES LCD Mod project you linked is demonstrating it with a Russian clone zapper.

I still don't understand what the second "button" is supposed to represent, though? You can't represent what the zapper's light sensor is doing with an on-off poll through USB. That is just not enough input information to do anything useful with any zapper game. The game software is based on the complex near-zero-latency stream of info through the TV->gun->$4017. It needs to change mid-frame at very specific times for the software to work.

So... for this emulator to handle raw hardware input, you need sub-frame polling with timing synchronized to the framerate, and either some kinda zero-latency display device, or some very advanced kinda frame-rewinding feature that interacts with that sub-frame polling. All of these features are more or less "impossible" to ever implement in this emulator, in my opinion.


Otherwise if you're not interested in it working with any older games, and only want it to work with new NES software specifically designed for high-latency and very coarse inputs, like those NES LCD Mod software patches, I guess that could be done with an input that is just "light was seen this frame" maybe? Is that what you're looking to do?

If that's the cause, the route I'd suggest would not be configuration for the existing NES Zapper input option, but adding a new "high latency zapper" or something that is just 2 assignable buttons. That wouldn't be that hard, it'd be pretty similar to any of the other existing controller option implementations.

**Comment by JasonWThompson** [comment] 2020-07-17 16:51
Perfect! Thank you for the info. I'll use that as a guide to implement my new "controller". I'll create a PR when it is ready.

**Comment by JasonWThompson** [comment] 2020-07-17 17:22
I like the idea of adding a new device. I think that's going to ultimately be cleaner. I've changed the name of the issue to reflect this.  I think my lunch is over with, so I'll start coding this up after work. 😁

**Comment by JasonWThompson** [comment] 2020-07-19 04:46
Hot dog! I got everything working. I submitted a pull request to integrate this into master: https://github.com/TASVideos/fceux/pull/133

**Closed** 2020-10-09 09:38 UTC

**Comment by r57zone** [comment] 2021-05-06 21:29
It turned out that can connect a [light gun via Digispark](https://github.com/r57zone/Zapper-Light-Gun-PC). Maybe it will be useful to someone who stumbles upon this.

**Comment by Boojakascha** [comment] 2021-11-01 06:13
It turned out you can indeed use the non patched ROMs on PC using Jason's code and a non filtering gun. For more information see ticket 133 (linked issue).
